version: '3.7'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres
  mongo:
    container_name: container-mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rently_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rently_123
      - ME_CONFIG_MONGODB_URL=mongodb://rently_user:rently_123@mongo:27017/?authMechanism=DEFAULT&authSource=rently_db
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "6060:8081"
  keycloak:
    image: jboss/keycloak:latest
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: compose-postgres
      DB_USER: compose-postgres
      DB_SCHEMA: public
      DB_PASSWORD: compose-postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8300:8080"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rently.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /var/lib/pgadmin